### ISSUE TITLE
Create a 'site plan' for BoO

### ISSUE THREAD

**Issue by jodinewman** [ForetCapitaleForest/actions#590] opened 2024-01-17 13:42 UTC
Create a site plan for the Base of Operations with things such as our proposed compost pile, soil/mulch dropoff bays, proposed shed locations, tree nursery, etc. 

Can be provided to JF to outline future plans and help with operational efficiency.

(P.S., once the site plan is finalized Jodi can use AutoCAD to help make different areas look distinct if we want)

**Comment by smlambert** [comment] 2024-01-17 13:58
re: AutoCAD offer, yes we want ! (if it doesn't take too much time/effort for @jodinewman)

**Comment by jodinewman** [comment] 2024-01-22 18:26
[Site Plan](https://drive.google.com/file/d/1Q3kD7lbC9Lz3MyiohlEi22gyKagSCPoE/view?usp=drive_link), let me know of any corrections or changes!

**Comment by smlambert** [comment] 2024-01-22 19:17
Some notes:
- Waking Path (spelling) -> Walking Path
- Would prefer to denote the Tiny Forest Demonstration Plots as 4 independent tennis court, co-located plots on maps (to avoid the confusion by anyone, including new team members who see this map that we only have 1 tiny forest at the base of operations) (in all other mention, including in the UofGuelph study, they are numbered Plot 1 through 4 starting at farm road and moving towards Innes, with an additional reference plot (also tennis court sized) staked out on the Innes side of Demo Plot 4. 
- Noting that there were trees planted in previous years in Field 2 where the aggregates pile is proposed, we should endeavour to find and flag any.  Does aggregates pile imply wood chips and leaf mulch brought in by external people?  if so, we should plan for it to be easy and safe for them to drop them, that location looks too deep into Field 2 to be accessible by their trucks.
- Noting that the compost pile area is an area that Moe had asked me to reserve for some other group or persons compost efforts (Box of Life or Jim or some combo).  This is what I would like to discuss with her, as we also need and plan to use lots of compost.  We should not plan to build infrastructure in this zone, in case she fluctuates on what it is destined for (I do not think we should build infra for our compost effort, [double-aerated block system](https://www.youtube.com/watch?v=Bg0CXHT6kQk) works better and works in smaller sites anyway).
- For the gate access, and 'road extension' suggestion, that will require funding and NCC, so I had not planned that for 2024, but I did give Moe a heads up that it is on our wish list, so its good to have it on the map
- we may also want to mark out the staff area / picnic table behind the FCF greenhouse, and the Nanabush seedling area behind the Nanabush greenhouse, and also the "A Cultivated Art" seedling area behind those

**Comment by jodinewman** [comment] 2024-01-23 20:15
See [Updated map](https://drive.google.com/file/d/1LsErmD3Avg0sZqvNSfeqc_TSQU9NS7xh/view?usp=drive_link)

Changes made:
- spelling correction
- Separated the tiny forest into 4 plots and added numbers. Also added in the tiniest tiny forest (numbered 5)
- Aggregates pile includes wood chips, leaf mulch, top soil, and our personal compost. Added this description to legend. 
   - Also moved aggregates pile to front of seedling area
- Compost pile area was intended to be the compost Moe is proposing, i have renamed this "Community Compost" in the legend
- Added "2025" to proposed gate access in legend
- Marked off nanabush seedling area and A Cultivated Art behind greenhouses (staff area was already marked off)

**Comment by smlambert** [comment] 2024-01-23 22:58
Awesome!  ( thanks @jodinewman looks good !)

**Closed** 2024-01-29 13:40 UTC
Labels: site:BoO

**Comment by smlambert** [comment] 2024-01-29 21:48
@jodinewman - could I ask for 1 last addition to the map?  

Can you include the proposed spots for seating (half log benches, 2 near the front entrance, 1 near the Cedar song sign, 2 at the Soil Living Lab).  

Also, there was the original intent to put 2 seats (simple cut log segments) in each of the 4 Tiny Forest demonstration plots (an unplanted circle was intended for each of the 4 plots, connected by a path, 2 of these 1.5 metre diameter circles coincide with where 2 malaise traps were situated).

**Comment by jodinewman** [comment] 2024-01-31 17:49
[Updated](https://drive.google.com/file/d/1agqO6CKznNI_6RqfzGbKGuPj02CjckFx/view?usp=drive_link), not 100% sure if the locations for the benches and seating are correct
