### ISSUE TITLE
Project Reporting NCC

### ISSUE THREAD

**Issue by StephMcNeely** [ForetCapitaleForest/actions#113] opened 2022-07-21 02:09 UTC

**Comment by smlambert** [comment] 2023-06-06 02:23
Is this the same as the 365 report tracked by this issue? https://github.com/ForetCapitaleForest/actions/issues/29
If so, we can likely close this one as duplicate.  If not, we should put some description in place to know what it is referring to

**Comment by smlambert** [comment] 2023-11-14 21:24
Temporarily assigning to @StephMcNeely to determine if its a duplicate of https://github.com/ForetCapitaleForest/actions/issues/29 and if it can be closed.

**Comment by smlambert** [comment] 2024-01-04 18:48
Will close this issue as a dup of other issue.

**Closed by smlambert** 2024-01-04 18:47 UTC
